apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    app: {{ template "mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "mysql.fullname" . }}
{{- with .Values.mysql.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.mysql.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.mysql.imagePullSecrets | indent 8 }}
      {{- end }}
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.25.0"
        imagePullPolicy: {{ .Values.mysql.imagePullPolicy | quote }}
        command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          {{- if .Values.mysql.persistence.subPath }}
          subPath: {{ .Values.mysql.persistence.subPath }}
          {{- end }}
      {{- if .Values.mysql.extraInitContainers }}
{{ tpl .Values.mysql.extraInitContainers . | indent 6 }}
      {{- end }}
      {{- if .Values.mysql.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.mysql.nodeSelector | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "mysql.fullname" . }}
        image: "{{ template "mysql.image" . }}"
        imagePullPolicy: {{ .Values.mysql.imagePullPolicy | quote }}
        resources:
{{ toYaml .Values.mysql.resources | indent 10 }}
        env:
        {{- if .Values.mysql.mysqlAllowEmptyPassword }}
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        {{- else }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.secretName" . }}
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.secretName" . }}
              key: mysql-password
        {{- end }}
        - name: MYSQL_USER
          value: {{ default "" .Values.mysql.mysqlUser | quote }}
        - name: MYSQL_DATABASE
          value: {{ default "" .Values.mysql.mysqlDatabase | quote }}
        {{- if .Values.mysql.timezone }}
        - name: TZ
          value: {{ .Values.mysql.timezone }}
        {{- end }}
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            {{- if .Values.mysql.mysqlAllowEmptyPassword }}
            - mysqladmin
            - ping
            {{- else }}
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            {{- end }}
          initialDelaySeconds: {{ .Values.mysql.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.mysql.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.mysql.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.mysql.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.mysql.livenessProbe.failureThreshold }}
        readinessProbe:
          exec:
            command:
            {{- if .Values.mysql.mysqlAllowEmptyPassword }}
            - mysqladmin
            - ping
            {{- else }}
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            {{- end }}
          initialDelaySeconds: {{ .Values.mysql.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.mysql.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.mysql.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.mysql.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.mysql.readinessProbe.failureThreshold }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          {{- if .Values.mysql.persistence.subPath }}
          subPath: {{ .Values.mysql.persistence.subPath }}
          {{- end }}
        {{- if .Values.mysql.configurationFiles }}
        - name: configurations
          mountPath: /etc/mysql/conf.d
        {{- end }}
        {{- if .Values.mysql.initializationFiles }}
        - name: migrations
          mountPath: /docker-entrypoint-initdb.d
        {{- end }}
        {{- if .Values.mysql.extraVolumeMounts }}
{{ tpl .Values.mysql.extraVolumeMounts . | indent 8 }}
        {{- end }}
      {{- if .Values.mysql.metrics.enabled }}
      - name: metrics
        image: "{{ template "mysql.metric.image" . }}"
        imagePullPolicy: {{ .Values.mysql.metrics.imagePullPolicy | quote }}
        {{- if .Values.mysql.mysqlAllowEmptyPassword }}
        command: [ 'sh', '-c', 'DATA_SOURCE_NAME="root@(localhost:3306)/" /bin/mysqld_exporter' ]
        {{- else }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.fullname" . }}
              key: mysql-root-password
        command: [ 'sh', '-c', 'DATA_SOURCE_NAME="root:$MYSQL_ROOT_PASSWORD@(localhost:3306)/" /bin/mysqld_exporter' ]
        {{- end }}
        ports:
        - name: metrics
          containerPort: 9104
        livenessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: {{ .Values.mysql.metrics.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.mysql.metrics.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: {{ .Values.mysql.metrics.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.mysql.metrics.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.mysql.metrics.resources | indent 10 }}
      {{- end }}
      volumes:
      {{- if .Values.mysql.configurationFiles }}
      - name: configurations
        configMap:
          name: {{ template "mysql.fullname" . }}-configuration
      {{- end }}
      {{- if .Values.mysql.initializationFiles }}
      - name: migrations
        configMap:
          name: {{ template "mysql.fullname" . }}-initialization
      {{- end }}
      - name: data
      {{- if .Values.mysql.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.mysql.persistence.existingClaim | default (include "mysql.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
      {{- if .Values.mysql.extraVolumes }}
{{ tpl .Values.mysql.extraVolumes . | indent 6 }}
      {{- end }}
