name: phpmyadmin-mysql
version: 1.0.0
appVersion: 4.8.2
description: phpMyAdmin is an mysql administration frontend
home: https://www.phpmyadmin.net/
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/PhpMyAdmin_logo.svg/800px-PhpMyAdmin_logo.svg.png
sources:
- https://github.com/bitnami/bitnami-docker-phpmyadmin
maintainers:
- name: amin-biabanaki
  email: aminbiabanaki@yahoo.com
engine: gotpl
